//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitchDownloaderWPF.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwitchDownloaderWPF.Translations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Queue.
        /// </summary>
        public static string AddToQueue {
            get {
                return ResourceManager.GetString("AddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve selected an alpha channel (transparency) for a container/codec that does not support it.\nRemove transparency or encode with MOV and RLE/PRORES (file size will be large).
        /// </summary>
        public static string AlphaNotSupportedByCodec {
            get {
                return ResourceManager.GetString("AlphaNotSupportedByCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string ApplicationLanguage {
            get {
                return ResourceManager.GetString("ApplicationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme .
        /// </summary>
        public static string ApplicationTheme {
            get {
                return ResourceManager.GetString("ApplicationTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to learn how to make your own theme!.
        /// </summary>
        public static string ApplicationThemeTooltip {
            get {
                return ResourceManager.GetString("ApplicationThemeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available parameteres are:.
        /// </summary>
        public static string AvailableParameters {
            get {
                return ResourceManager.GetString("AvailableParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color:.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Scale:.
        /// </summary>
        public static string BadgeScale {
            get {
                return ResourceManager.GetString("BadgeScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned Words List .
        /// </summary>
        public static string BannedWordsList {
            get {
                return ResourceManager.GetString("BannedWordsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of banned words or phrases - comma separated, spaces around commas ignored, NOT case-sensitive..
        /// </summary>
        public static string BannedWordsListTooltip {
            get {
                return ResourceManager.GetString("BannedWordsListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTTV Emotes:.
        /// </summary>
        public static string BttvEmotes {
            get {
                return ResourceManager.GetString("BttvEmotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Folder:.
        /// </summary>
        public static string CacheFolder {
            get {
                return ResourceManager.GetString("CacheFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Badge Filter:.
        /// </summary>
        public static string ChatBadgeFilter {
            get {
                return ResourceManager.GetString("ChatBadgeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Badges:.
        /// </summary>
        public static string ChatBadges {
            get {
                return ResourceManager.GetString("ChatBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression:.
        /// </summary>
        public static string ChatCompression {
            get {
                return ResourceManager.GetString("ChatCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gzip.
        /// </summary>
        public static string ChatCompressionGzip {
            get {
                return ResourceManager.GetString("ChatCompressionGzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ChatCompressionNone {
            get {
                return ResourceManager.GetString("ChatCompressionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop:.
        /// </summary>
        public static string ChatCrop {
            get {
                return ResourceManager.GetString("ChatCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Download.
        /// </summary>
        public static string ChatDownload {
            get {
                return ResourceManager.GetString("ChatDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Downloads.
        /// </summary>
        public static string ChatDownloads {
            get {
                return ResourceManager.GetString("ChatDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font:.
        /// </summary>
        public static string ChatFont {
            get {
                return ResourceManager.GetString("ChatFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size:.
        /// </summary>
        public static string ChatFontSize {
            get {
                return ResourceManager.GetString("ChatFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string ChatHeight {
            get {
                return ResourceManager.GetString("ChatHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Render.
        /// </summary>
        public static string ChatRender {
            get {
                return ResourceManager.GetString("ChatRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Renders.
        /// </summary>
        public static string ChatRenders {
            get {
                return ResourceManager.GetString("ChatRenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Update.
        /// </summary>
        public static string ChatUpdate {
            get {
                return ResourceManager.GetString("ChatUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Updater.
        /// </summary>
        public static string ChatUpdater {
            get {
                return ResourceManager.GetString("ChatUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string ChatWidth {
            get {
                return ResourceManager.GetString("ChatWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear your cache?\nYou should only really do this if the program isn&apos;t working correctly.
        /// </summary>
        public static string ClearCacheConfirmation {
            get {
                return ResourceManager.GetString("ClearCacheConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip Download.
        /// </summary>
        public static string ClipDownload {
            get {
                return ResourceManager.GetString("ClipDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip Downloads.
        /// </summary>
        public static string ClipDownloads {
            get {
                return ResourceManager.GetString("ClipDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip Link/ID:.
        /// </summary>
        public static string ClipLinkId {
            get {
                return ResourceManager.GetString("ClipLinkId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string CropEnd {
            get {
                return ResourceManager.GetString("CropEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string CropStart {
            get {
                return ResourceManager.GetString("CropStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Video:.
        /// </summary>
        public static string CropVideo {
            get {
                return ResourceManager.GetString("CropVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date_custom formatting is based on the.
        /// </summary>
        public static string DateCustomFormatting {
            get {
                return ResourceManager.GetString("DateCustomFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# standard date and time format strings.
        /// </summary>
        public static string DateCustomFormattingHyperlink {
            get {
                return ResourceManager.GetString("DateCustomFormattingHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the program often and want to support me? Buy me a coffee :).
        /// </summary>
        public static string DonateTooltip {
            get {
                return ResourceManager.GetString("DonateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Chat.
        /// </summary>
        public static string DownloadChat {
            get {
                return ResourceManager.GetString("DownloadChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections:.
        /// </summary>
        public static string DownloadConnections {
            get {
                return ResourceManager.GetString("DownloadConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Filename Templates:.
        /// </summary>
        public static string DownloadFilenameTemplates {
            get {
                return ResourceManager.GetString("DownloadFilenameTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Folder:.
        /// </summary>
        public static string DownloadFolder {
            get {
                return ResourceManager.GetString("DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Format:.
        /// </summary>
        public static string DownloadFormat {
            get {
                return ResourceManager.GetString("DownloadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Threads:.
        /// </summary>
        public static string DownloadThreads {
            get {
                return ResourceManager.GetString("DownloadThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Video.
        /// </summary>
        public static string DownloadVideo {
            get {
                return ResourceManager.GetString("DownloadVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed Images .
        /// </summary>
        public static string EmbedImages {
            get {
                return ResourceManager.GetString("EmbedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed first party emotes, badges, and cheermotes into the download file for offline rendering. Useful for archival purposes, file size will be larger..
        /// </summary>
        public static string EmbedImagesTooltip {
            get {
                return ResourceManager.GetString("EmbedImagesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed Missing .
        /// </summary>
        public static string EmbedMissing {
            get {
                return ResourceManager.GetString("EmbedMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embeds missing emotes, badges, and cheermotes. Already embedded images will be untouched..
        /// </summary>
        public static string EmbedMissingTooltip {
            get {
                return ResourceManager.GetString("EmbedMissingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emoji Scale:.
        /// </summary>
        public static string EmojiScale {
            get {
                return ResourceManager.GetString("EmojiScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote Scale:.
        /// </summary>
        public static string EmoteScale {
            get {
                return ResourceManager.GetString("EmoteScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote Spacing Scale:.
        /// </summary>
        public static string EmoteSpacingScale {
            get {
                return ResourceManager.GetString("EmoteSpacingScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue Download.
        /// </summary>
        public static string EnqueueDownload {
            get {
                return ResourceManager.GetString("EnqueueDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue Render.
        /// </summary>
        public static string EnqueueRender {
            get {
                return ResourceManager.GetString("EnqueueRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue Update.
        /// </summary>
        public static string EnqueueUpdate {
            get {
                return ResourceManager.GetString("EnqueueUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: .
        /// </summary>
        public static string ErrorLog {
            get {
                return ResourceManager.GetString("ErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        public static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Arguments:.
        /// </summary>
        public static string FfmpegInputArguments {
            get {
                return ResourceManager.GetString("FfmpegInputArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to learn about Ffmpeg options.
        /// </summary>
        public static string FfmpegOptionsHyperlink {
            get {
                return ResourceManager.GetString("FfmpegOptionsHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputArguments:.
        /// </summary>
        public static string FfmpegOutputArguments {
            get {
                return ResourceManager.GetString("FfmpegOutputArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {fps} {height} {width} {max_int} {save_path}.
        /// </summary>
        public static string FfmpegParameters {
            get {
                return ResourceManager.GetString("FfmpegParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset To Defaults.
        /// </summary>
        public static string FfmpegReset {
            get {
                return ResourceManager.GetString("FfmpegReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFZ Emotes:.
        /// </summary>
        public static string FfzEmotes {
            get {
                return ResourceManager.GetString("FfzEmotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {title} {id} {date} {channel} {date_custom=&quot;&quot;} {random_string}.
        /// </summary>
        public static string FilenameTemplateParameters {
            get {
                return ResourceManager.GetString("FilenameTemplateParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found: .
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color:.
        /// </summary>
        public static string FontColor {
            get {
                return ResourceManager.GetString("FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Mask:.
        /// </summary>
        public static string GenerateMask {
            get {
                return ResourceManager.GetString("GenerateMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Info.
        /// </summary>
        public static string GetInfo {
            get {
                return ResourceManager.GetString("GetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Donation Button:.
        /// </summary>
        public static string HideDonationButton {
            get {
                return ResourceManager.GetString("HideDonationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Indent Scale:.
        /// </summary>
        public static string HighlightIndentScale {
            get {
                return ResourceManager.GetString("HighlightIndentScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Stoke Scale:.
        /// </summary>
        public static string HighlightStrokeScale {
            get {
                return ResourceManager.GetString("HighlightStrokeScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Users List .
        /// </summary>
        public static string IgnoreUsersList {
            get {
                return ResourceManager.GetString("IgnoreUsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of usernames - comma separated, spaces around commas ignored, NOT case-sensitive..
        /// </summary>
        public static string IgnoreUsersListTooltip {
            get {
                return ResourceManager.GetString("IgnoreUsersListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Clip Link/ID.
        /// </summary>
        public static string InvalidClipLinkId {
            get {
                return ResourceManager.GetString("InvalidClipLinkId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid clip Link/ID\nExamples:\nhttps://clips.twitch.tv/ImportantPlausibleMetalOSsloth\nImportantPlausibleMetalOSsloth.
        /// </summary>
        public static string InvalidClipLinkIdMessage {
            get {
                return ResourceManager.GetString("InvalidClipLinkIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Crop Inputs.
        /// </summary>
        public static string InvalidCropInputs {
            get {
                return ResourceManager.GetString("InvalidCropInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid start or end time.
        /// </summary>
        public static string InvalidStartEndTime {
            get {
                return ResourceManager.GetString("InvalidStartEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Video Link/ID.
        /// </summary>
        public static string InvalidVideoLinkId {
            get {
                return ResourceManager.GetString("InvalidVideoLinkId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid video Link/ID\nExamples:\nhttps://www.twitch.tv/videos/470741744\n470741744.
        /// </summary>
        public static string InvalidVideoLinkIdMessage {
            get {
                return ResourceManager.GetString("InvalidVideoLinkIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON File:.
        /// </summary>
        public static string JsonFile {
            get {
                return ResourceManager.GetString("JsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of VODs/Clips (One per line).
        /// </summary>
        public static string ListOfVodsClips {
            get {
                return ResourceManager.GetString("ListOfVodsClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log:.
        /// </summary>
        public static string LogHeader {
            get {
                return ResourceManager.GetString("LogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass Downloads.
        /// </summary>
        public static string MassDownloads {
            get {
                return ResourceManager.GetString("MassDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispersion .
        /// </summary>
        public static string MessageDispersion {
            get {
                return ResourceManager.GetString("MessageDispersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In November 2022 a Twitch API change made chat messages download only in whole seconds. If there are multiple messages on a second, they will be intelligently distributed over the second to improve chat flow..
        /// </summary>
        public static string MessageDispersionTooltip {
            get {
                return ResourceManager.GetString("MessageDispersionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth (optional) .
        /// </summary>
        public static string Oauth {
            get {
                return ResourceManager.GetString("Oauth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only required for sub only VODs. All 3rd party OAuth tokens will not work. Click to see YouTube video on how to get OAuth token..
        /// </summary>
        public static string OAuthTooltip {
            get {
                return ResourceManager.GetString("OAuthTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline .
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render the chat using only resources embedded in the chat json file..
        /// </summary>
        public static string OfflineTooltip {
            get {
                return ResourceManager.GetString("OfflineTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline:.
        /// </summary>
        public static string Outline {
            get {
                return ResourceManager.GetString("Outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel Task Limits.
        /// </summary>
        public static string ParallelTaskLimits {
            get {
                return ResourceManager.GetString("ParallelTaskLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Render.
        /// </summary>
        public static string PartialRender {
            get {
                return ResourceManager.GetString("PartialRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality:.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render.
        /// </summary>
        public static string Render {
            get {
                return ResourceManager.GetString("Render", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Chat.
        /// </summary>
        public static string RenderChat {
            get {
                return ResourceManager.GetString("RenderChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec:.
        /// </summary>
        public static string RenderCodec {
            get {
                return ResourceManager.GetString("RenderCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is for advanced users only. If you get a pipe ended error this is probably why..
        /// </summary>
        public static string RenderFfmpegWarning {
            get {
                return ResourceManager.GetString("RenderFfmpegWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Format:.
        /// </summary>
        public static string RenderFileFormat {
            get {
                return ResourceManager.GetString("RenderFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate:.
        /// </summary>
        public static string RenderFramerate {
            get {
                return ResourceManager.GetString("RenderFramerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        public static string RenderTabEncoding {
            get {
                return ResourceManager.GetString("RenderTabEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ffmpeg.
        /// </summary>
        public static string RenderTabFfmpeg {
            get {
                return ResourceManager.GetString("RenderTabFfmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string RenderTabGeneral {
            get {
                return ResourceManager.GetString("RenderTabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string RenderTabPreview {
            get {
                return ResourceManager.GetString("RenderTabPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering.
        /// </summary>
        public static string RenderTabRendering {
            get {
                return ResourceManager.GetString("RenderTabRendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling.
        /// </summary>
        public static string RenderTabScaling {
            get {
                return ResourceManager.GetString("RenderTabScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width and Height must be even.
        /// </summary>
        public static string RenderWidthHeightMustBeEven {
            get {
                return ResourceManager.GetString("RenderWidthHeightMustBeEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Embeds .
        /// </summary>
        public static string ReplaceEmbeds {
            get {
                return ResourceManager.GetString("ReplaceEmbeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace all embedded emotes, badges, and cheermotes in the file. All embedded images will be overwritten!.
        /// </summary>
        public static string ReplaceEmbedsTooltip {
            get {
                return ResourceManager.GetString("ReplaceEmbedsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Clips.
        /// </summary>
        public static string SearchClips {
            get {
                return ResourceManager.GetString("SearchClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search VODs.
        /// </summary>
        public static string SearchVods {
            get {
                return ResourceManager.GetString("SearchVods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Height Scale:.
        /// </summary>
        public static string SectionHeightScale {
            get {
                return ResourceManager.GetString("SectionHeightScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Items:.
        /// </summary>
        public static string SelectedItems {
            get {
                return ResourceManager.GetString("SelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Channel.
        /// </summary>
        public static string SetChannel {
            get {
                return ResourceManager.GetString("SetChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side Padding Scale:.
        /// </summary>
        public static string SidePaddingScale {
            get {
                return ResourceManager.GetString("SidePaddingScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort:.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string StatusDone {
            get {
                return ResourceManager.GetString("StatusDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string StatusDownloading {
            get {
                return ResourceManager.GetString("StatusDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string StatusError {
            get {
                return ResourceManager.GetString("StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string StatusIdle {
            get {
                return ResourceManager.GetString("StatusIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering.
        /// </summary>
        public static string StatusRendering {
            get {
                return ResourceManager.GetString("StatusRendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        public static string StatusUpdating {
            get {
                return ResourceManager.GetString("StatusUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streamer:.
        /// </summary>
        public static string Streamer {
            get {
                return ResourceManager.GetString("Streamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7TV Emotes:.
        /// </summary>
        public static string StvEmotes {
            get {
                return ResourceManager.GetString("StvEmotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Messages:.
        /// </summary>
        public static string SubMessages {
            get {
                return ResourceManager.GetString("SubMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TaskCancel {
            get {
                return ResourceManager.GetString("TaskCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TaskError {
            get {
                return ResourceManager.GetString("TaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Queue.
        /// </summary>
        public static string TaskQueue {
            get {
                return ResourceManager.GetString("TaskQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats:.
        /// </summary>
        public static string TemplateChats {
            get {
                return ResourceManager.GetString("TemplateChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clips:.
        /// </summary>
        public static string TemplateClips {
            get {
                return ResourceManager.GetString("TemplateClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VODs:.
        /// </summary>
        public static string TemplateVods {
            get {
                return ResourceManager.GetString("TemplateVods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme not found.
        /// </summary>
        public static string ThemeNotFound {
            get {
                return ResourceManager.GetString("ThemeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {theme} was not found. Reverting theme to System.
        /// </summary>
        public static string ThemeNotFoundMessage {
            get {
                return ResourceManager.GetString("ThemeNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd Party Emotes .
        /// </summary>
        public static string ThirdPartyEmotes {
            get {
                return ResourceManager.GetString("ThirdPartyEmotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also embed third party emotes into the file. File size will be much larger..
        /// </summary>
        public static string ThirdPartyEmotesTooltip {
            get {
                return ResourceManager.GetString("ThirdPartyEmotesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp Format:.
        /// </summary>
        public static string TimestampFormat {
            get {
                return ResourceManager.GetString("TimestampFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string TimestampNone {
            get {
                return ResourceManager.GetString("TimestampNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative.
        /// </summary>
        public static string TimestampRelative {
            get {
                return ResourceManager.GetString("TimestampRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamps:.
        /// </summary>
        public static string Timestamps {
            get {
                return ResourceManager.GetString("Timestamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC.
        /// </summary>
        public static string TimestampUtc {
            get {
                return ResourceManager.GetString("TimestampUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top All Time.
        /// </summary>
        public static string TopAllTime {
            get {
                return ResourceManager.GetString("TopAllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 7 Days.
        /// </summary>
        public static string TopSevenDays {
            get {
                return ResourceManager.GetString("TopSevenDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 30 Days.
        /// </summary>
        public static string TopThirtyDays {
            get {
                return ResourceManager.GetString("TopThirtyDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 24 Hours.
        /// </summary>
        public static string TopTwentyFourHours {
            get {
                return ResourceManager.GetString("TopTwentyFourHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Find Thumbnail.
        /// </summary>
        public static string UnableToFindThumbnail {
            get {
                return ResourceManager.GetString("UnableToFindThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get Clip information. Please double check Clip Slug and try again.
        /// </summary>
        public static string UnableToGetClipInfo {
            get {
                return ResourceManager.GetString("UnableToGetClipInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get info.
        /// </summary>
        public static string UnableToGetInfo {
            get {
                return ResourceManager.GetString("UnableToGetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get Video/Clip information. Please double check your link and try again.
        /// </summary>
        public static string UnableToGetInfoMessage {
            get {
                return ResourceManager.GetString("UnableToGetInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get video information. Please make sure the Link/ID is correct and try again..
        /// </summary>
        public static string UnableToGetVideoInfo {
            get {
                return ResourceManager.GetString("UnableToGetVideoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse inputs.
        /// </summary>
        public static string UnableToParseInputs {
            get {
                return ResourceManager.GetString("UnableToParseInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please double check your inputs are valid.
        /// </summary>
        public static string UnableToParseInputsMessage {
            get {
                return ResourceManager.GetString("UnableToParseInputsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse link.
        /// </summary>
        public static string UnableToParseLink {
            get {
                return ResourceManager.GetString("UnableToParseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please double check the VOD/Clip link.
        /// </summary>
        public static string UnableToParseLinkMessage {
            get {
                return ResourceManager.GetString("UnableToParseLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Rate:.
        /// </summary>
        public static string UpdateRate {
            get {
                return ResourceManager.GetString("UpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL List.
        /// </summary>
        public static string UrlList {
            get {
                return ResourceManager.GetString("UrlList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose Error Output.
        /// </summary>
        public static string VerboseErrorOutput {
            get {
                return ResourceManager.GetString("VerboseErrorOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose Errors:.
        /// </summary>
        public static string VerboseErrors {
            get {
                return ResourceManager.GetString("VerboseErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Spacing Scale:.
        /// </summary>
        public static string VerticalSpacingScale {
            get {
                return ResourceManager.GetString("VerticalSpacingScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        public static string VideoCreatedAt {
            get {
                return ResourceManager.GetString("VideoCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string VideoTitle {
            get {
                return ResourceManager.GetString("VideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOD/Clip Link:.
        /// </summary>
        public static string VodClipLink {
            get {
                return ResourceManager.GetString("VodClipLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOD Download.
        /// </summary>
        public static string VodDownload {
            get {
                return ResourceManager.GetString("VodDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOD Downloads.
        /// </summary>
        public static string VodDownloads {
            get {
                return ResourceManager.GetString("VodDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video is expired or embedded ID is corrupt.
        /// </summary>
        public static string VodExpiredOrIdCorrupt {
            get {
                return ResourceManager.GetString("VodExpiredOrIdCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOD Link/ID:.
        /// </summary>
        public static string VodLinkId {
            get {
                return ResourceManager.GetString("VodLinkId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Spacing Scale:.
        /// </summary>
        public static string WordSpacingScale {
            get {
                return ResourceManager.GetString("WordSpacingScale", resourceCulture);
            }
        }
    }
}
