//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitchDownloaderWPF.Translations {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwitchDownloaderWPF.Translations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Accept 的本地化字符串。
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add To Queue 的本地化字符串。
        /// </summary>
        public static string AddToQueue {
            get {
                return ResourceManager.GetString("AddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;ve selected an alpha channel (transparency) for a container/codec that does not support it. Remove transparency or encode with MOV + RLE/PRORES or WEBM + VP8/VP9 的本地化字符串。
        /// </summary>
        public static string AlphaNotSupportedByCodec {
            get {
                return ResourceManager.GetString("AlphaNotSupportedByCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language  的本地化字符串。
        /// </summary>
        public static string ApplicationLanguage {
            get {
                return ResourceManager.GetString("ApplicationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is TwitchDownloaderWPF not available in your native language? Click to learn how to help translate! 的本地化字符串。
        /// </summary>
        public static string ApplicationLanguageTooltip {
            get {
                return ResourceManager.GetString("ApplicationLanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme  的本地化字符串。
        /// </summary>
        public static string ApplicationTheme {
            get {
                return ResourceManager.GetString("ApplicationTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to learn how to make your own theme! 的本地化字符串。
        /// </summary>
        public static string ApplicationThemeTooltip {
            get {
                return ResourceManager.GetString("ApplicationThemeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available parameters are: 的本地化字符串。
        /// </summary>
        public static string AvailableParameters {
            get {
                return ResourceManager.GetString("AvailableParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background Color: 的本地化字符串。
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Badge Scale: 的本地化字符串。
        /// </summary>
        public static string BadgeScale {
            get {
                return ResourceManager.GetString("BadgeScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Banned Words List  的本地化字符串。
        /// </summary>
        public static string BannedWordsList {
            get {
                return ResourceManager.GetString("BannedWordsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List of banned words or phrases - comma separated, spaces around commas ignored, NOT case-sensitive. 的本地化字符串。
        /// </summary>
        public static string BannedWordsListTooltip {
            get {
                return ResourceManager.GetString("BannedWordsListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BTTV Emotes: 的本地化字符串。
        /// </summary>
        public static string BttvEmotes {
            get {
                return ResourceManager.GetString("BttvEmotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cache Folder: 的本地化字符串。
        /// </summary>
        public static string CacheFolder {
            get {
                return ResourceManager.GetString("CacheFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chat Badge Filter: 的本地化字符串。
        /// </summary>
        public static string ChatBadgeFilter {
            get {
                return ResourceManager.GetString("ChatBadgeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chat Badges: 的本地化字符串。
        /// </summary>
        public static string ChatBadges {
            get {
                return ResourceManager.GetString("ChatBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compression: 的本地化字符串。
        /// </summary>
        public static string ChatCompression {
            get {
                return ResourceManager.GetString("ChatCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gzip 的本地化字符串。
        /// </summary>
        public static string ChatCompressionGzip {
            get {
                return ResourceManager.GetString("ChatCompressionGzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string ChatCompressionNone {
            get {
                return ResourceManager.GetString("ChatCompressionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crop: 的本地化字符串。
        /// </summary>
        public static string ChatCrop {
            get {
                return ResourceManager.GetString("ChatCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chat Download 的本地化字符串。
        /// </summary>
        public static string ChatDownload {
            get {
                return ResourceManager.GetString("ChatDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chat Downloads 的本地化字符串。
        /// </summary>
        public static string ChatDownloads {
            get {
                return ResourceManager.GetString("ChatDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font: 的本地化字符串。
        /// </summary>
        public static string ChatFont {
            get {
                return ResourceManager.GetString("ChatFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Size: 的本地化字符串。
        /// </summary>
        public static string ChatFontSize {
            get {
                return ResourceManager.GetString("ChatFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height: 的本地化字符串。
        /// </summary>
        public static string ChatHeight {
            get {
                return ResourceManager.GetString("ChatHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chat Render 的本地化字符串。
        /// </summary>
        public static string ChatRender {
            get {
                return ResourceManager.GetString("ChatRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chat Renders 的本地化字符串。
        /// </summary>
        public static string ChatRenders {
            get {
                return ResourceManager.GetString("ChatRenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chat Update 的本地化字符串。
        /// </summary>
        public static string ChatUpdate {
            get {
                return ResourceManager.GetString("ChatUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chat Updater 的本地化字符串。
        /// </summary>
        public static string ChatUpdater {
            get {
                return ResourceManager.GetString("ChatUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width: 的本地化字符串。
        /// </summary>
        public static string ChatWidth {
            get {
                return ResourceManager.GetString("ChatWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to clear your cache?\nYou should only really do this if the program isn&apos;t working correctly 的本地化字符串。
        /// </summary>
        public static string ClearCacheConfirmation {
            get {
                return ResourceManager.GetString("ClearCacheConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clip Download 的本地化字符串。
        /// </summary>
        public static string ClipDownload {
            get {
                return ResourceManager.GetString("ClipDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clip Downloads 的本地化字符串。
        /// </summary>
        public static string ClipDownloads {
            get {
                return ResourceManager.GetString("ClipDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clip Link/ID: 的本地化字符串。
        /// </summary>
        public static string ClipLinkId {
            get {
                return ResourceManager.GetString("ClipLinkId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End 的本地化字符串。
        /// </summary>
        public static string CropEnd {
            get {
                return ResourceManager.GetString("CropEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string CropStart {
            get {
                return ResourceManager.GetString("CropStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crop Video: 的本地化字符串。
        /// </summary>
        public static string CropVideo {
            get {
                return ResourceManager.GetString("CropVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 date_custom formatting is based on the 的本地化字符串。
        /// </summary>
        public static string DateCustomFormatting {
            get {
                return ResourceManager.GetString("DateCustomFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C# standard date and time format strings 的本地化字符串。
        /// </summary>
        public static string DateCustomFormattingHyperlink {
            get {
                return ResourceManager.GetString("DateCustomFormattingHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Confirmation 的本地化字符串。
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use the program often and want to support me? Buy me a coffee :) 的本地化字符串。
        /// </summary>
        public static string DonateTooltip {
            get {
                return ResourceManager.GetString("DonateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Chat 的本地化字符串。
        /// </summary>
        public static string DownloadChat {
            get {
                return ResourceManager.GetString("DownloadChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connections: 的本地化字符串。
        /// </summary>
        public static string DownloadConnections {
            get {
                return ResourceManager.GetString("DownloadConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Filename Templates: 的本地化字符串。
        /// </summary>
        public static string DownloadFilenameTemplates {
            get {
                return ResourceManager.GetString("DownloadFilenameTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Folder: 的本地化字符串。
        /// </summary>
        public static string DownloadFolder {
            get {
                return ResourceManager.GetString("DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Format: 的本地化字符串。
        /// </summary>
        public static string DownloadFormat {
            get {
                return ResourceManager.GetString("DownloadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Threads: 的本地化字符串。
        /// </summary>
        public static string DownloadThreads {
            get {
                return ResourceManager.GetString("DownloadThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Video 的本地化字符串。
        /// </summary>
        public static string DownloadVideo {
            get {
                return ResourceManager.GetString("DownloadVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embed Images  的本地化字符串。
        /// </summary>
        public static string EmbedImages {
            get {
                return ResourceManager.GetString("EmbedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embed first party emotes, badges, and cheermotes into the download file for offline rendering. Useful for archival purposes, file size will be larger. 的本地化字符串。
        /// </summary>
        public static string EmbedImagesTooltip {
            get {
                return ResourceManager.GetString("EmbedImagesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embed Missing  的本地化字符串。
        /// </summary>
        public static string EmbedMissing {
            get {
                return ResourceManager.GetString("EmbedMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embeds missing emotes, badges, and cheermotes. Already embedded images will be untouched. 的本地化字符串。
        /// </summary>
        public static string EmbedMissingTooltip {
            get {
                return ResourceManager.GetString("EmbedMissingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emoji Scale: 的本地化字符串。
        /// </summary>
        public static string EmojiScale {
            get {
                return ResourceManager.GetString("EmojiScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emoji Vendor: 的本地化字符串。
        /// </summary>
        public static string EmojiVendor {
            get {
                return ResourceManager.GetString("EmojiVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string EmojiVendorNone {
            get {
                return ResourceManager.GetString("EmojiVendorNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Google 的本地化字符串。
        /// </summary>
        public static string EmojiVendorNotoColor {
            get {
                return ResourceManager.GetString("EmojiVendorNotoColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Twitter 的本地化字符串。
        /// </summary>
        public static string EmojiVendorTwemoji {
            get {
                return ResourceManager.GetString("EmojiVendorTwemoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emote Scale: 的本地化字符串。
        /// </summary>
        public static string EmoteScale {
            get {
                return ResourceManager.GetString("EmoteScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emote Spacing Scale: 的本地化字符串。
        /// </summary>
        public static string EmoteSpacingScale {
            get {
                return ResourceManager.GetString("EmoteSpacingScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enqueue Download 的本地化字符串。
        /// </summary>
        public static string EnqueueDownload {
            get {
                return ResourceManager.GetString("EnqueueDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enqueue Render 的本地化字符串。
        /// </summary>
        public static string EnqueueRender {
            get {
                return ResourceManager.GetString("EnqueueRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enqueue Update 的本地化字符串。
        /// </summary>
        public static string EnqueueUpdate {
            get {
                return ResourceManager.GetString("EnqueueUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR:  的本地化字符串。
        /// </summary>
        public static string ErrorLog {
            get {
                return ResourceManager.GetString("ErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fatal Error 的本地化字符串。
        /// </summary>
        public static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Arguments: 的本地化字符串。
        /// </summary>
        public static string FfmpegInputArguments {
            get {
                return ResourceManager.GetString("FfmpegInputArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here to learn about Ffmpeg options 的本地化字符串。
        /// </summary>
        public static string FfmpegOptionsHyperlink {
            get {
                return ResourceManager.GetString("FfmpegOptionsHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Arguments: 的本地化字符串。
        /// </summary>
        public static string FfmpegOutputArguments {
            get {
                return ResourceManager.GetString("FfmpegOutputArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {fps} {height} {width} {max_int} {save_path} 的本地化字符串。
        /// </summary>
        public static string FfmpegParameters {
            get {
                return ResourceManager.GetString("FfmpegParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset To Defaults 的本地化字符串。
        /// </summary>
        public static string FfmpegReset {
            get {
                return ResourceManager.GetString("FfmpegReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FFZ Emotes: 的本地化字符串。
        /// </summary>
        public static string FfzEmotes {
            get {
                return ResourceManager.GetString("FfzEmotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {title} {id} {date} {channel} {date_custom=&quot;&quot;} {random_string} {crop_start} {crop_end} {crop_start_custom=&quot;&quot;} {crop_end_custom=&quot;&quot;} 的本地化字符串。
        /// </summary>
        public static string FilenameTemplateParameters {
            get {
                return ResourceManager.GetString("FilenameTemplateParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Not Found:  的本地化字符串。
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Color: 的本地化字符串。
        /// </summary>
        public static string FontColor {
            get {
                return ResourceManager.GetString("FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Mask: 的本地化字符串。
        /// </summary>
        public static string GenerateMask {
            get {
                return ResourceManager.GetString("GenerateMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Info 的本地化字符串。
        /// </summary>
        public static string GetInfo {
            get {
                return ResourceManager.GetString("GetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Donation Button: 的本地化字符串。
        /// </summary>
        public static string HideDonationButton {
            get {
                return ResourceManager.GetString("HideDonationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Highlight Indent Scale: 的本地化字符串。
        /// </summary>
        public static string HighlightIndentScale {
            get {
                return ResourceManager.GetString("HighlightIndentScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Highlight Stroke Scale: 的本地化字符串。
        /// </summary>
        public static string HighlightStrokeScale {
            get {
                return ResourceManager.GetString("HighlightStrokeScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore Users List  的本地化字符串。
        /// </summary>
        public static string IgnoreUsersList {
            get {
                return ResourceManager.GetString("IgnoreUsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List of usernames - comma separated, spaces around commas ignored, NOT case-sensitive. 的本地化字符串。
        /// </summary>
        public static string IgnoreUsersListTooltip {
            get {
                return ResourceManager.GetString("IgnoreUsersListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient access. OAuth may be required. 的本地化字符串。
        /// </summary>
        public static string InsufficientAccessMayNeedOauth {
            get {
                return ResourceManager.GetString("InsufficientAccessMayNeedOauth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Clip Link/ID 的本地化字符串。
        /// </summary>
        public static string InvalidClipLinkId {
            get {
                return ResourceManager.GetString("InvalidClipLinkId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a valid clip Link/ID\nExamples:\nhttps://clips.twitch.tv/ImportantPlausibleMetalOSsloth\nImportantPlausibleMetalOSsloth 的本地化字符串。
        /// </summary>
        public static string InvalidClipLinkIdMessage {
            get {
                return ResourceManager.GetString("InvalidClipLinkIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Crop Inputs 的本地化字符串。
        /// </summary>
        public static string InvalidCropInputs {
            get {
                return ResourceManager.GetString("InvalidCropInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Folder Path 的本地化字符串。
        /// </summary>
        public static string InvalidFolderPath {
            get {
                return ResourceManager.GetString("InvalidFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid start or end time 的本地化字符串。
        /// </summary>
        public static string InvalidStartEndTime {
            get {
                return ResourceManager.GetString("InvalidStartEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Video Link/ID 的本地化字符串。
        /// </summary>
        public static string InvalidVideoLinkId {
            get {
                return ResourceManager.GetString("InvalidVideoLinkId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a valid video Link/ID\nExamples:\nhttps://www.twitch.tv/videos/470741744\n470741744 的本地化字符串。
        /// </summary>
        public static string InvalidVideoLinkIdMessage {
            get {
                return ResourceManager.GetString("InvalidVideoLinkIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The folder does not exist 的本地化字符串。
        /// </summary>
        public static string InvaliFolderPathMessage {
            get {
                return ResourceManager.GetString("InvaliFolderPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JSON File: 的本地化字符串。
        /// </summary>
        public static string JsonFile {
            get {
                return ResourceManager.GetString("JsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length: 的本地化字符串。
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List of VODs/Clips (One per line) 的本地化字符串。
        /// </summary>
        public static string ListOfVodsClips {
            get {
                return ResourceManager.GetString("ListOfVodsClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log: 的本地化字符串。
        /// </summary>
        public static string LogHeader {
            get {
                return ResourceManager.GetString("LogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;ve selected generate mask with an opaque background. Reduce the background color alpha or disable generate mask. 的本地化字符串。
        /// </summary>
        public static string MaskWithNoAlpha {
            get {
                return ResourceManager.GetString("MaskWithNoAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mass Downloads 的本地化字符串。
        /// </summary>
        public static string MassDownloads {
            get {
                return ResourceManager.GetString("MassDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum Thread Bandwidth  的本地化字符串。
        /// </summary>
        public static string MaximumThreadBandwidth {
            get {
                return ResourceManager.GetString("MaximumThreadBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum bandwidth that new download threads will be allowed to use, in kibibytes per second. 的本地化字符串。
        /// </summary>
        public static string MaximumThreadBandwidthTooltip {
            get {
                return ResourceManager.GetString("MaximumThreadBandwidthTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dispersion  的本地化字符串。
        /// </summary>
        public static string MessageDispersion {
            get {
                return ResourceManager.GetString("MessageDispersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In November 2022 a Twitch API change made chat messages download only in whole seconds. If there are multiple messages on a second, they will be intelligently distributed over the second to improve chat flow. 的本地化字符串。
        /// </summary>
        public static string MessageDispersionTooltip {
            get {
                return ResourceManager.GetString("MessageDispersionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No JSON files selected 的本地化字符串。
        /// </summary>
        public static string NoJsonFilesSelected {
            get {
                return ResourceManager.GetString("NoJsonFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OAuth (optional)  的本地化字符串。
        /// </summary>
        public static string Oauth {
            get {
                return ResourceManager.GetString("Oauth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only required for sub only VODs. All 3rd party OAuth tokens will not work. Click to see YouTube video on how to get OAuth token. 的本地化字符串。
        /// </summary>
        public static string OAuthTooltip {
            get {
                return ResourceManager.GetString("OAuthTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offline  的本地化字符串。
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Render the chat using only resources embedded in the chat json file. 的本地化字符串。
        /// </summary>
        public static string OfflineTooltip {
            get {
                return ResourceManager.GetString("OfflineTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outline: 的本地化字符串。
        /// </summary>
        public static string Outline {
            get {
                return ResourceManager.GetString("Outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outline Scale: 的本地化字符串。
        /// </summary>
        public static string OutlineScale {
            get {
                return ResourceManager.GetString("OutlineScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parallel Task Limits 的本地化字符串。
        /// </summary>
        public static string ParallelTaskLimits {
            get {
                return ResourceManager.GetString("ParallelTaskLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partial Render 的本地化字符串。
        /// </summary>
        public static string PartialRender {
            get {
                return ResourceManager.GetString("PartialRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality: 的本地化字符串。
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Render 的本地化字符串。
        /// </summary>
        public static string Render {
            get {
                return ResourceManager.GetString("Render", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Render Chat 的本地化字符串。
        /// </summary>
        public static string RenderChat {
            get {
                return ResourceManager.GetString("RenderChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Codec: 的本地化字符串。
        /// </summary>
        public static string RenderCodec {
            get {
                return ResourceManager.GetString("RenderCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is for advanced users only. If you get a pipe ended error this is probably why. 的本地化字符串。
        /// </summary>
        public static string RenderFfmpegWarning {
            get {
                return ResourceManager.GetString("RenderFfmpegWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Format: 的本地化字符串。
        /// </summary>
        public static string RenderFileFormat {
            get {
                return ResourceManager.GetString("RenderFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Framerate: 的本地化字符串。
        /// </summary>
        public static string RenderFramerate {
            get {
                return ResourceManager.GetString("RenderFramerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sharpening: 的本地化字符串。
        /// </summary>
        public static string RenderImageSharpening {
            get {
                return ResourceManager.GetString("RenderImageSharpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encoding 的本地化字符串。
        /// </summary>
        public static string RenderTabEncoding {
            get {
                return ResourceManager.GetString("RenderTabEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ffmpeg 的本地化字符串。
        /// </summary>
        public static string RenderTabFfmpeg {
            get {
                return ResourceManager.GetString("RenderTabFfmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string RenderTabGeneral {
            get {
                return ResourceManager.GetString("RenderTabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        public static string RenderTabPreview {
            get {
                return ResourceManager.GetString("RenderTabPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rendering 的本地化字符串。
        /// </summary>
        public static string RenderTabRendering {
            get {
                return ResourceManager.GetString("RenderTabRendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scaling 的本地化字符串。
        /// </summary>
        public static string RenderTabScaling {
            get {
                return ResourceManager.GetString("RenderTabScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width and Height must be even 的本地化字符串。
        /// </summary>
        public static string RenderWidthHeightMustBeEven {
            get {
                return ResourceManager.GetString("RenderWidthHeightMustBeEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace Embeds  的本地化字符串。
        /// </summary>
        public static string ReplaceEmbeds {
            get {
                return ResourceManager.GetString("ReplaceEmbeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace all embedded emotes, badges, and cheermotes in the file. All embedded images will be overwritten! 的本地化字符串。
        /// </summary>
        public static string ReplaceEmbedsTooltip {
            get {
                return ResourceManager.GetString("ReplaceEmbedsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Clips 的本地化字符串。
        /// </summary>
        public static string SearchClips {
            get {
                return ResourceManager.GetString("SearchClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search VODs 的本地化字符串。
        /// </summary>
        public static string SearchVods {
            get {
                return ResourceManager.GetString("SearchVods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Section Height Scale: 的本地化字符串。
        /// </summary>
        public static string SectionHeightScale {
            get {
                return ResourceManager.GetString("SectionHeightScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected Items: 的本地化字符串。
        /// </summary>
        public static string SelectedItems {
            get {
                return ResourceManager.GetString("SelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Channel 的本地化字符串。
        /// </summary>
        public static string SetChannel {
            get {
                return ResourceManager.GetString("SetChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time Format: 的本地化字符串。
        /// </summary>
        public static string SettingsTimeFormat {
            get {
                return ResourceManager.GetString("SettingsTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Side Padding Scale: 的本地化字符串。
        /// </summary>
        public static string SidePaddingScale {
            get {
                return ResourceManager.GetString("SidePaddingScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort: 的本地化字符串。
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canceled 的本地化字符串。
        /// </summary>
        public static string StatusCanceled {
            get {
                return ResourceManager.GetString("StatusCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canceling 的本地化字符串。
        /// </summary>
        public static string StatusCanceling {
            get {
                return ResourceManager.GetString("StatusCanceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        public static string StatusDone {
            get {
                return ResourceManager.GetString("StatusDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading 的本地化字符串。
        /// </summary>
        public static string StatusDownloading {
            get {
                return ResourceManager.GetString("StatusDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR 的本地化字符串。
        /// </summary>
        public static string StatusError {
            get {
                return ResourceManager.GetString("StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle 的本地化字符串。
        /// </summary>
        public static string StatusIdle {
            get {
                return ResourceManager.GetString("StatusIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rendering 的本地化字符串。
        /// </summary>
        public static string StatusRendering {
            get {
                return ResourceManager.GetString("StatusRendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updating 的本地化字符串。
        /// </summary>
        public static string StatusUpdating {
            get {
                return ResourceManager.GetString("StatusUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Streamer: 的本地化字符串。
        /// </summary>
        public static string Streamer {
            get {
                return ResourceManager.GetString("Streamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7TV Emotes: 的本地化字符串。
        /// </summary>
        public static string StvEmotes {
            get {
                return ResourceManager.GetString("StvEmotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sub Messages: 的本地化字符串。
        /// </summary>
        public static string SubMessages {
            get {
                return ResourceManager.GetString("SubMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string TaskCancel {
            get {
                return ResourceManager.GetString("TaskCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string TaskError {
            get {
                return ResourceManager.GetString("TaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task Queue 的本地化字符串。
        /// </summary>
        public static string TaskQueue {
            get {
                return ResourceManager.GetString("TaskQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chats: 的本地化字符串。
        /// </summary>
        public static string TemplateChats {
            get {
                return ResourceManager.GetString("TemplateChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clips: 的本地化字符串。
        /// </summary>
        public static string TemplateClips {
            get {
                return ResourceManager.GetString("TemplateClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VODs: 的本地化字符串。
        /// </summary>
        public static string TemplateVods {
            get {
                return ResourceManager.GetString("TemplateVods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme not found 的本地化字符串。
        /// </summary>
        public static string ThemeNotFound {
            get {
                return ResourceManager.GetString("ThemeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {theme} was not found. Reverting theme to System 的本地化字符串。
        /// </summary>
        public static string ThemeNotFoundMessage {
            get {
                return ResourceManager.GetString("ThemeNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some included themes failed to write. 的本地化字符串。
        /// </summary>
        public static string ThemesFailedToWrite {
            get {
                return ResourceManager.GetString("ThemesFailedToWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3rd Party Emotes  的本地化字符串。
        /// </summary>
        public static string ThirdPartyEmotes {
            get {
                return ResourceManager.GetString("ThirdPartyEmotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Also embed third party emotes into the file. File size will be much larger. 的本地化字符串。
        /// </summary>
        public static string ThirdPartyEmotesTooltip {
            get {
                return ResourceManager.GetString("ThirdPartyEmotesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 crop_start_custom and crop_end_custom formattings are based on the 的本地化字符串。
        /// </summary>
        public static string TimeSpanCustomFormatting {
            get {
                return ResourceManager.GetString("TimeSpanCustomFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C# standard TimeSpan format strings 的本地化字符串。
        /// </summary>
        public static string TimeSpanCustomFormattingHyperlink {
            get {
                return ResourceManager.GetString("TimeSpanCustomFormattingHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timestamp Format: 的本地化字符串。
        /// </summary>
        public static string TimestampFormat {
            get {
                return ResourceManager.GetString("TimestampFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local 的本地化字符串。
        /// </summary>
        public static string TimestampLocal {
            get {
                return ResourceManager.GetString("TimestampLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string TimestampNone {
            get {
                return ResourceManager.GetString("TimestampNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relative 的本地化字符串。
        /// </summary>
        public static string TimestampRelative {
            get {
                return ResourceManager.GetString("TimestampRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timestamps: 的本地化字符串。
        /// </summary>
        public static string Timestamps {
            get {
                return ResourceManager.GetString("Timestamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UTC 的本地化字符串。
        /// </summary>
        public static string TimestampUtc {
            get {
                return ResourceManager.GetString("TimestampUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clip Mass Downloader 的本地化字符串。
        /// </summary>
        public static string TitleClipMassDownloader {
            get {
                return ResourceManager.GetString("TitleClipMassDownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enqueue Options 的本地化字符串。
        /// </summary>
        public static string TitleEnqueueOptions {
            get {
                return ResourceManager.GetString("TitleEnqueueOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global Settings 的本地化字符串。
        /// </summary>
        public static string TitleGlobalSettings {
            get {
                return ResourceManager.GetString("TitleGlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Render Rage (Seconds) 的本地化字符串。
        /// </summary>
        public static string TitleRenderRange {
            get {
                return ResourceManager.GetString("TitleRenderRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mass Download URL List 的本地化字符串。
        /// </summary>
        public static string TitleUrlList {
            get {
                return ResourceManager.GetString("TitleUrlList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video Mass Downloader 的本地化字符串。
        /// </summary>
        public static string TitleVideoMassDownloader {
            get {
                return ResourceManager.GetString("TitleVideoMassDownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top All Time 的本地化字符串。
        /// </summary>
        public static string TopAllTime {
            get {
                return ResourceManager.GetString("TopAllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 7 Days 的本地化字符串。
        /// </summary>
        public static string TopSevenDays {
            get {
                return ResourceManager.GetString("TopSevenDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 30 Days 的本地化字符串。
        /// </summary>
        public static string TopThirtyDays {
            get {
                return ResourceManager.GetString("TopThirtyDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 24 Hours 的本地化字符串。
        /// </summary>
        public static string TopTwentyFourHours {
            get {
                return ResourceManager.GetString("TopTwentyFourHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to find thumbnail 的本地化字符串。
        /// </summary>
        public static string UnableToFindThumbnail {
            get {
                return ResourceManager.GetString("UnableToFindThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to get Clip information. Please double check Clip ID and try again. 的本地化字符串。
        /// </summary>
        public static string UnableToGetClipInfo {
            get {
                return ResourceManager.GetString("UnableToGetClipInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to get info 的本地化字符串。
        /// </summary>
        public static string UnableToGetInfo {
            get {
                return ResourceManager.GetString("UnableToGetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to get Video/Clip information. Please double check your link and try again 的本地化字符串。
        /// </summary>
        public static string UnableToGetInfoMessage {
            get {
                return ResourceManager.GetString("UnableToGetInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to get video information. Please make sure the Link/ID is correct and try again. 的本地化字符串。
        /// </summary>
        public static string UnableToGetVideoInfo {
            get {
                return ResourceManager.GetString("UnableToGetVideoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to parse inputs 的本地化字符串。
        /// </summary>
        public static string UnableToParseInputs {
            get {
                return ResourceManager.GetString("UnableToParseInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please double check your inputs are valid 的本地化字符串。
        /// </summary>
        public static string UnableToParseInputsMessage {
            get {
                return ResourceManager.GetString("UnableToParseInputsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to parse link 的本地化字符串。
        /// </summary>
        public static string UnableToParseLink {
            get {
                return ResourceManager.GetString("UnableToParseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please double check the VOD/Clip link 的本地化字符串。
        /// </summary>
        public static string UnableToParseLinkMessage {
            get {
                return ResourceManager.GetString("UnableToParseLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Rate: 的本地化字符串。
        /// </summary>
        public static string UpdateRate {
            get {
                return ResourceManager.GetString("UpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL List 的本地化字符串。
        /// </summary>
        public static string UrlList {
            get {
                return ResourceManager.GetString("UrlList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verbose Error Output 的本地化字符串。
        /// </summary>
        public static string VerboseErrorOutput {
            get {
                return ResourceManager.GetString("VerboseErrorOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verbose Errors: 的本地化字符串。
        /// </summary>
        public static string VerboseErrors {
            get {
                return ResourceManager.GetString("VerboseErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertical Spacing Scale: 的本地化字符串。
        /// </summary>
        public static string VerticalSpacingScale {
            get {
                return ResourceManager.GetString("VerticalSpacingScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created: 的本地化字符串。
        /// </summary>
        public static string VideoCreatedAt {
            get {
                return ResourceManager.GetString("VideoCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title: 的本地化字符串。
        /// </summary>
        public static string VideoTitle {
            get {
                return ResourceManager.GetString("VideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VOD/Clip Link: 的本地化字符串。
        /// </summary>
        public static string VodClipLink {
            get {
                return ResourceManager.GetString("VodClipLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VOD Download 的本地化字符串。
        /// </summary>
        public static string VodDownload {
            get {
                return ResourceManager.GetString("VodDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VOD Downloads 的本地化字符串。
        /// </summary>
        public static string VodDownloads {
            get {
                return ResourceManager.GetString("VodDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video is expired or embedded ID is corrupt 的本地化字符串。
        /// </summary>
        public static string VodExpiredOrIdCorrupt {
            get {
                return ResourceManager.GetString("VodExpiredOrIdCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VOD Link/ID: 的本地化字符串。
        /// </summary>
        public static string VodLinkId {
            get {
                return ResourceManager.GetString("VodLinkId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Word Spacing Scale: 的本地化字符串。
        /// </summary>
        public static string WordSpacingScale {
            get {
                return ResourceManager.GetString("WordSpacingScale", resourceCulture);
            }
        }
    }
}
