namespace TwitchDownloaderAvalonia.Services
{
    internal static class ThemePackPalettes
    {
        public const string SAMPLE_AUTHOR = "TwitchDownloader";

        public static readonly IReadOnlyDictionary<string, string> Light = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["WindowBackgroundBrush"] = "#F4F2F7",
            ["WindowForegroundBrush"] = "#18181B",
            ["SidebarBackgroundBrush"] = "#EBE6F2",
            ["StatusBarBackgroundBrush"] = "#FFFFFF",
            ["CardBackgroundBrush"] = "#FFFFFF",
            ["CardMutedBrush"] = "#EFEAF6",
            ["InputBackgroundBrush"] = "#F7F5FA",
            ["BorderBrush"] = "#D9D4E3",
            ["AccentBrush"] = "#9146FF",
            ["AccentHoverBrush"] = "#772CE8",
            ["AccentForegroundBrush"] = "#FFFFFF",
            ["NavSelectedBrush"] = "#9146FF",
            ["NavHoverBrush"] = "#E4DDF0",
            ["CardSelectedBrush"] = "#E8DCFF",
            ["CardSelectedHoverBrush"] = "#DCC9FF",
            ["MutedForegroundBrush"] = "#6B6480",
            ["LiveBadgeBackgroundBrush"] = "#EB0400",
            ["LiveBadgeForegroundBrush"] = "#FFFFFF",
            ["HighlightBrush"] = "#9146FF",
            ["HighlightForegroundBrush"] = "#FFFFFF",
            ["ThemeBackgroundBrush"] = "#F4F2F7",
            ["ThemeForegroundBrush"] = "#18181B",
            ["ThemeAccentBrush"] = "#9146FF",
            ["ThemeAccentBrush2"] = "#CC9146FF",
            ["ThemeAccentBrush3"] = "#B39146FF",
            ["ThemeAccentBrush4"] = "#809146FF",
            ["ThemeControlHighlightMidBrush"] = "#E4DDF0",
            ["ThemeBorderLowBrush"] = "#D9D4E3",
            ["ThemeBorderMidBrush"] = "#D9D4E3",
            ["ThemeBorderHighBrush"] = "#B8B0C8",
            ["ThemeControlMidBrush"] = "#FFFFFF",
            ["ThemeControlHighBrush"] = "#EBE6F2",
        };

        public static readonly IReadOnlyDictionary<string, string> Dark = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["WindowBackgroundBrush"] = "#1C1C21",
            ["WindowForegroundBrush"] = "#EFEFF1",
            ["SidebarBackgroundBrush"] = "#161619",
            ["StatusBarBackgroundBrush"] = "#25252B",
            ["CardBackgroundBrush"] = "#25252B",
            ["CardMutedBrush"] = "#2E2E36",
            ["InputBackgroundBrush"] = "#1C1C21",
            ["BorderBrush"] = "#3A3A44",
            ["AccentBrush"] = "#9146FF",
            ["AccentHoverBrush"] = "#A970FF",
            ["AccentForegroundBrush"] = "#FFFFFF",
            ["NavSelectedBrush"] = "#9146FF",
            ["NavHoverBrush"] = "#2A2A32",
            ["CardSelectedBrush"] = "#3A2754",
            ["CardSelectedHoverBrush"] = "#4A3380",
            ["MutedForegroundBrush"] = "#9B9BA8",
            ["LiveBadgeBackgroundBrush"] = "#EB0400",
            ["LiveBadgeForegroundBrush"] = "#FFFFFF",
            ["HighlightBrush"] = "#9146FF",
            ["HighlightForegroundBrush"] = "#FFFFFF",
            ["ThemeBackgroundBrush"] = "#1C1C21",
            ["ThemeForegroundBrush"] = "#EFEFF1",
            ["ThemeAccentBrush"] = "#9146FF",
            ["ThemeAccentBrush2"] = "#CC9146FF",
            ["ThemeAccentBrush3"] = "#B39146FF",
            ["ThemeAccentBrush4"] = "#809146FF",
            ["ThemeControlHighlightMidBrush"] = "#2A2A32",
            ["ThemeBorderLowBrush"] = "#3A3A44",
            ["ThemeBorderMidBrush"] = "#3A3A44",
            ["ThemeBorderHighBrush"] = "#5A5A68",
            ["ThemeControlMidBrush"] = "#25252B",
            ["ThemeControlHighBrush"] = "#2E2E36",
        };

        public static readonly IReadOnlyDictionary<string, string> LightPink = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["WindowBackgroundBrush"] = "#FDF2F8",
            ["WindowForegroundBrush"] = "#4A154B",
            ["SidebarBackgroundBrush"] = "#FCE7F3",
            ["StatusBarBackgroundBrush"] = "#FFFFFF",
            ["CardBackgroundBrush"] = "#FFFFFF",
            ["CardMutedBrush"] = "#FCE7F3",
            ["InputBackgroundBrush"] = "#FFF7FB",
            ["BorderBrush"] = "#F9A8D4",
            ["AccentBrush"] = "#DB2777",
            ["AccentHoverBrush"] = "#BE185D",
            ["AccentForegroundBrush"] = "#FFFFFF",
            ["NavSelectedBrush"] = "#DB2777",
            ["NavHoverBrush"] = "#FBCFE8",
            ["CardSelectedBrush"] = "#FBCFE8",
            ["CardSelectedHoverBrush"] = "#F9A8D4",
            ["MutedForegroundBrush"] = "#9D4E7A",
            ["LiveBadgeBackgroundBrush"] = "#EB0400",
            ["LiveBadgeForegroundBrush"] = "#FFFFFF",
            ["HighlightBrush"] = "#DB2777",
            ["HighlightForegroundBrush"] = "#FFFFFF",
            ["ThemeBackgroundBrush"] = "#FDF2F8",
            ["ThemeForegroundBrush"] = "#4A154B",
            ["ThemeAccentBrush"] = "#DB2777",
            ["ThemeAccentBrush2"] = "#CCDB2777",
            ["ThemeAccentBrush3"] = "#B3DB2777",
            ["ThemeAccentBrush4"] = "#80DB2777",
            ["ThemeControlHighlightMidBrush"] = "#FBCFE8",
            ["ThemeBorderLowBrush"] = "#F9A8D4",
            ["ThemeBorderMidBrush"] = "#F9A8D4",
            ["ThemeBorderHighBrush"] = "#F472B6",
            ["ThemeControlMidBrush"] = "#FFFFFF",
            ["ThemeControlHighBrush"] = "#FCE7F3",
        };

        public static readonly IReadOnlyDictionary<string, string> DarkPink = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["WindowBackgroundBrush"] = "#1A1016",
            ["WindowForegroundBrush"] = "#FDF2F8",
            ["SidebarBackgroundBrush"] = "#140C11",
            ["StatusBarBackgroundBrush"] = "#251820",
            ["CardBackgroundBrush"] = "#251820",
            ["CardMutedBrush"] = "#322028",
            ["InputBackgroundBrush"] = "#1A1016",
            ["BorderBrush"] = "#5C3348",
            ["AccentBrush"] = "#F472B6",
            ["AccentHoverBrush"] = "#F9A8D4",
            ["AccentForegroundBrush"] = "#1A1016",
            ["NavSelectedBrush"] = "#F472B6",
            ["NavHoverBrush"] = "#3A2430",
            ["CardSelectedBrush"] = "#5C2344",
            ["CardSelectedHoverBrush"] = "#7A2D5A",
            ["MutedForegroundBrush"] = "#E8A0C0",
            ["LiveBadgeBackgroundBrush"] = "#EB0400",
            ["LiveBadgeForegroundBrush"] = "#FFFFFF",
            ["HighlightBrush"] = "#F472B6",
            ["HighlightForegroundBrush"] = "#1A1016",
            ["ThemeBackgroundBrush"] = "#1A1016",
            ["ThemeForegroundBrush"] = "#FDF2F8",
            ["ThemeAccentBrush"] = "#F472B6",
            ["ThemeAccentBrush2"] = "#CCF472B6",
            ["ThemeAccentBrush3"] = "#B3F472B6",
            ["ThemeAccentBrush4"] = "#80F472B6",
            ["ThemeControlHighlightMidBrush"] = "#3A2430",
            ["ThemeBorderLowBrush"] = "#5C3348",
            ["ThemeBorderMidBrush"] = "#5C3348",
            ["ThemeBorderHighBrush"] = "#9D4E7A",
            ["ThemeControlMidBrush"] = "#251820",
            ["ThemeControlHighBrush"] = "#322028",
        };

        public static readonly ThemePackSample[] Samples =
        [
            new("Light Pink.json", false, LightPink),
            new("Dark Pink.json", true, DarkPink),
        ];
    }

    internal readonly record struct ThemePackSample(string FileName, bool IsDark, IReadOnlyDictionary<string, string> Colors);
}
